variables:
  GIT_SUBMODULE_STRATEGY: recursive

workspace:
  stage: build
  script:
    - rm -rf build install 
    - ./container.sh --platform=linux/arm64 ./build.sh

  artifacts:
    paths:
      - install/
