variables:
  GIT_SUBMODULE_STRATEGY: recursive

workspace:
  stage: build
  script:
    - mkdir -p cross_compile/out/{arm64,amd64}
    - docker buildx build --platform linux/amd64 -f Dockerfile.cross --output cross_compile/out/amd64 .
    - docker buildx build --platform linux/arm64 -f Dockerfile.cross --output cross_compile/out/arm64 .