variables:
  GIT_SUBMODULE_STRATEGY: recursive

default:
  before_script:
    - podman unshare git clean -fdx

workspace-x86:
  stage: build
  script:
    - |
      ./container.sh \
        --engine=podman \
        ./build.sh

    #- ./scripts/ostree-push.sh linux/amd64 $CI_COMMIT_REF_NAME
  artifacts:
    paths:
      - install/

workspace-arm64:
  stage: build
  script:
    - |
      ./container.sh \
        --engine=podman \
        --image=docker.io/rccn/usr-cross-compile \
        ./cross-build.sh

    #- ./scripts/ostree-push.sh $PLATFORM $CI_COMMIT_REF_NAME

  artifacts:
    paths:
      - install/target
