variables:
  GIT_SUBMODULE_STRATEGY: recursive

workspace:
  stage: build
  script:
    - rm -rf build install 
    - ./container.sh --platform=$PLATFORM ./build.sh
    - ./scripts/ostree-push.sh $PLATFORM $CI_COMMIT_REF_NAME
  parallel:
    matrix:
      - PLATFORM: ["linux/amd64"] # ,linux-arm64

  artifacts:
    paths:
      - install/
