variables:
  GIT_SUBMODULE_STRATEGY: recursive

workspace:
  stage: build
  script:
    - mkdir -p build/out/{arm64,amd64}
    - rm $(find build/ -name ".cargo-lock")
    - docker buildx build --platform linux/amd64 -f Dockerfile.build --output build/out/amd64 .
    - docker buildx build --platform linux/arm64 -f Dockerfile.build --output build/out/arm64 .

  artifacts:
    paths:
      - build/out/amd64
      - build/out/arm64
