variables:
  GIT_SUBMODULE_STRATEGY: recursive

workspace:
  stage: build
  script:
    - rm -f $(find . -name "*.cargo-lock")
    - ./container.sh --platform=linux/arm64 ./build.sh

  artifacts:
    paths:
      - build/install
