variables:
  GIT_SUBMODULE_STRATEGY: recursive

workspace-x86:
  stage: build
  script:
    - git clean -fdx

    - |
      ./container.sh
        --engine=podman
        ./build.sh

    - ./scripts/ostree-push.sh $PLATFORM $CI_COMMIT_REF_NAME

  artifacts:
    paths:
      - install/

workspace-arm64:
  stage: build
  script:
    - git clean -fdx

    - |
      ./container.sh
        --engine=podman
        --image=docker.io/rccn/usr-cross-compile
        ./cross-compile.sh

    #- ./scripts/ostree-push.sh $PLATFORM $CI_COMMIT_REF_NAME

  artifacts:
    paths:
      - install/target
