[workspace]
resolver = "2"
members = [ "src/rccn_usr",
    "src/rccn_usr_comm"
, "src/rccn_usr_example_app", "src/rccn_usr_pus"]

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
strip = true
panic = "abort"
