FROM rccn-usr-base

ARG USERNAME=rosdev
ARG WORKSPACE=/home/rosdev/ros2_ws

# Switch to user
USER $USERNAME
WORKDIR /home/$USERNAME

# Install UV package manager and setup Python environment
RUN pip install uv \
    && ~/.local/bin/uv venv --python 3.10 .venv \
    && . .venv/bin/activate \
    && ~/.local/bin/uv pip install \
        git+https://github.com/colcon/colcon-cargo.git \
        git+https://github.com/colcon/colcon-ros-cargo.git \
        colcon-common-extensions \
        empy==3.3.4 \
        lark \
        numpy \
        Cython

# Setup shell environment
RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> ~/.bashrc \
    && echo "source $WORKSPACE/install/setup.bash" >> ~/.bashrc \
    && echo "source ~/.cargo/env" >> ~/.bashrc \
    && echo "source /home/$USERNAME/.venv/bin/activate" >> ~/.bashrc

# Setup entrypoint
#COPY --chown=$USERNAME:$USERNAME ./ros_entrypoint.sh /
#ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]
