frames:
  spacecraft_id: 0xAB

  in:
    frame_kind: tc
    transport:
      kind: udp
      listen: 127.0.0.1:10018

  out:
    frame_kind: uslp
    transport:
      kind: udp
      send: 127.0.0.1:10015

virtual_channels:
  - id: 0
    name: bus_realtime
    splitter: space_packet

    tx_transport:
      kind: ros2
      topic_pub: /vc/bus_realtime/rx
    rx_transport:
      kind: ros2
      topic_sub: /vc/bus_realtime/tx

  - id: 1
    name: cfdp

    tx_transport:
      kind: udp
      listen: 127.0.0.1:2000
    rx_transport:
      kind: udp
      send: 127.0.0.1:3000

  #- id: 2
  #  name: bus_history
  #  out_transport:
  #    kind: ros2
  #    action_srv: /vc/bus_history/downlink