name: RACCOON Userspace Workspace build & deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the workspace using docker
      run: mkdir -p deploy/build && docker build . -f Dockerfile.cross --platform linux/arm64 --output deploy/out
